### ISSUE TITLE
Return "Failed to connect to server" instead of the 'panic' below.

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/node-bindgen#1]
14:44:27.027 ERROR nj_core::basic > error executing napi call PendingException
thread '<unnamed>' panicked at 'napi call failed: napi call failed PendingException', <::std::macros::panic macros>:5:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6

**Comment by sehz** [comment]
fixed. it returns proper error:

[Error: IoError(
    Os {
        code: 60,
        kind: TimedOut,
        message: "Operation timed out",
    },
)].

We need ability specify timeout which will be address as separate issue.
