### ISSUE TITLE
Async functions without return values are resolved immediately

### ISSUE THREAD

**Issue by nickbabcock** [infinyon/node-bindgen#101]
I have a simple test repo: https://github.com/nickbabcock/node-bindgen-async-test

The code is a simple wrapper around sled to simulate a bit more of a real world example than the one found in this repo.

[The CI is extremely flaky](https://github.com/nickbabcock/node-bindgen-async-test/actions/runs/364578011), but if I change [everything to synchronous](https://github.com/nickbabcock/node-bindgen-async-test/commit/83427ae31a02e360b6e1a81183f0a9ff20a0f3e4) -- [tests pass no problem](https://github.com/nickbabcock/node-bindgen-async-test/actions/runs/364586684). It's almost as if nodejs isn't respecting the await

**Comment by sehz** [comment]
The code is sync but tests is async.  Is that correct?

**Comment by nickbabcock** [comment]
Yeah I just wanted to showcase the smallest diff. If the code goes full async the issue still persists.

**Comment by sehz** [comment]
Actually, surprised that it actually worked.   Native sync functional should be call with sync call.   Async function should be call with async call.

**Comment by nickbabcock** [comment]
Yeah sorry, I wasn't trying to draw too much attention to details the sync solution ([as `await` can be used for non-promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) -- if somewhat needlessly). I wanted to emphasize only that async glue seems is flaky while the same code behind sync methods is good.

**Comment by nickbabcock** [comment]
I further simplified the problem so that it looks almost exactly like the [example code](https://github.com/infinyon/node-bindgen/blob/master/examples/class-async/src/lib.rs) and still no dice: https://github.com/nickbabcock/node-bindgen-async-test/tree/async3

Let me know what you think, as I may need your expertise. Very puzzling 🤔

**Comment by sehz** [comment]
It worked for me after I changing line 2 of: `native-test.js`

`const { NativeStore } = require("../dist/index.node")`

to

`const { NativeStore } = require("../dist")

**Comment by nickbabcock** [comment]
Yeah, it tends to have a higher chance of passing locally than on CI. There doesn't seem to be any pattern in CI failures (ie: only node 12 or only windows, something like that). I applied your suggestion on this branch https://github.com/nickbabcock/node-bindgen-async-test/tree/async3 and the CI failures continue.

**Comment by sehz** [comment]
To debug further, can you put some logging statement in Rust code just before it is returning value?

**Comment by nickbabcock** [comment]
(Updating https://github.com/nickbabcock/node-bindgen-async-test/tree/async3 with logging)

Below is the output from a good test run:

```
INFO node_bindgen_async: 1 put async start
INFO node_bindgen_async: 2 put async start
INFO node_bindgen_async: 3 put async start
INFO node_bindgen_async: 4 get async start
INFO node_bindgen_async: 1 put async slept
INFO node_bindgen_async: 1 put async done
INFO node_bindgen_async: 2 put async slept
INFO node_bindgen_async: 3 put async slept
INFO node_bindgen_async: 2 put async done
INFO node_bindgen_async: 4 get async slept
INFO node_bindgen_async: 3 put async done
INFO node_bindgen_async: 4 get async done
INFO node_bindgen_async: 5 get async start
INFO node_bindgen_async: 5 get async slept
INFO node_bindgen_async: 5 get async done
INFO node_bindgen_async: 6 get async start
INFO node_bindgen_async: 6 get async slept
INFO node_bindgen_async: 6 get async done
INFO node_bindgen_async: 7 clear async start
INFO node_bindgen_async: 8 get async start
INFO node_bindgen_async: 7 clear async slept
INFO node_bindgen_async: 8 get async slept
INFO node_bindgen_async: 7 clear async done
INFO node_bindgen_async: 8 get async done
INFO node_bindgen_async: 9 get async start
INFO node_bindgen_async: 9 get async slept
INFO node_bindgen_async: 9 get async done
INFO node_bindgen_async: 10 get async start
INFO node_bindgen_async: 10 get async slept
INFO node_bindgen_async: 10 get async done  
```

And here is a failed one:

```
INFO node_bindgen_async: 1 put async start    
INFO node_bindgen_async: 2 put async start    
INFO node_bindgen_async: 3 put async start    
INFO node_bindgen_async: 4 get async start    
INFO node_bindgen_async: 1 put async slept    
INFO node_bindgen_async: 3 put async slept    
INFO node_bindgen_async: 3 put async done    
INFO node_bindgen_async: 2 put async slept    
INFO node_bindgen_async: 2 put async done    
INFO node_bindgen_async: 1 put async done    
INFO node_bindgen_async: 4 get async slept    
INFO node_bindgen_async: 4 get async done    
INFO node_bindgen_async: 5 get async start    
INFO node_bindgen_async: 5 get async slept    
INFO node_bindgen_async: 5 get async done    
INFO node_bindgen_async: 6 get async start    
INFO node_bindgen_async: 6 get async slept    
INFO node_bindgen_async: 6 get async done    
INFO node_bindgen_async: 7 clear async start    
INFO node_bindgen_async: 8 get async start    
INFO node_bindgen_async: 8 get async slept    
INFO node_bindgen_async: 8 get async done    
INFO node_bindgen_async: 7 clear async slept    
INFO node_bindgen_async: 7 clear async done    
INFO node_bindgen_async: 9 get async start    
INFO node_bindgen_async: 9 get async slept    
INFO node_bindgen_async: 9 get async done    
INFO node_bindgen_async: 10 get async start    
INFO node_bindgen_async: 10 get async slept    
INFO node_bindgen_async: 10 get async done 
```

In the bad run there should be 3 get requests after the `clear`, but one of the `get` is scheduled and finishes before the `clear` is finished

**Comment by sehz** [comment]
Have you try to reproduce bad run in your local machine?  Github CI is not reliable for running integration tests due to their limited CPU allowance.

**Comment by nickbabcock** [comment]
I've changed some sleep times in the repo (merged everything into master to make it easier for you to verify: https://github.com/nickbabcock/node-bindgen-async-test).

You should be able to replicate this error 100% of the time.

`await` is not being respected. It's almost as if the values node_bindgen is returning are not natively understood to be promises for some reason 😕

**Comment by nickbabcock** [comment]
So the bare minimum to reproduce this issue is to create a hashmap facade

```
await store.put("key", "value");
const val = await store.get("key");
```

And make `put` sleep 1 second (and no sleep on `get`). I did some logging and found that `put` and `get` are scheduled simultaneously:

```
Nov 18 20:13:05.004  INFO node_bindgen_async: put async start    
Nov 18 20:13:05.004  INFO node_bindgen_async: get async start    
Nov 18 20:13:05.004  INFO node_bindgen_async: get async done 
Nov 18 20:13:06.004  INFO node_bindgen_async: put async done 
```

This leads me to make a conjecture that node_bindgen could be resolving the `put` promise to undefined (as it knows it will be undefined due to no return value) but it resolves before the sleep has finished.

**Comment by sehz** [comment]
If you ever want to know what node_bindgen is doing, you can install [cargo-expand](https://github.com/dtolnay/cargo-expand) to show macro-expansion

**Comment by nickbabcock** [comment]
Yeah, this is what put expands to:

```rust
extern "C" fn napi_put(
    env: node_bindgen::sys::napi_env,
    cb_info: node_bindgen::sys::napi_callback_info,
) -> node_bindgen::sys::napi_value {
    use node_bindgen::core::TryIntoJs;
    use node_bindgen::core::IntoJs;
    use node_bindgen::core::val::JsCallbackFunction;
    let js_env = node_bindgen::core::val::JsEnv::new(env);
    let result: Result<node_bindgen::sys::napi_value, node_bindgen::core::NjError> =
        (move || {
            let mut js_cb = js_env.get_cb_info(cb_info, 2)?;
            let rust_value_0 = js_cb.get_value::<String>()?;
            let rust_value_1 = js_cb.get_value::<String>()?;
            let receiver = (js_cb.unwrap_mut::<Self>()?);
            node_bindgen::core::future::spawn(async move {
                receiver.put(rust_value_0, rust_value_1).await;
            });
            Ok(std::ptr::null_mut())
        })();
    result.to_js(&js_env)
}
```

The spawn looks suspect to me as I would expect something should get assigned to it.

**Comment by sehz** [comment]
can you add your test case to: https://github.com/infinyon/node-bindgen/tree/master/examples/promise after remove dependencies to sled?  It seems like returning undefined causing issue.

I can fix it or if you can try to fix if you are familiar with procedure macro

**Comment by sehz** [comment]
can you check if  https://github.com/infinyon/node-bindgen/pull/102 fixes the issue?  Perform `cargo update` and re-run your tests

**Comment by nickbabcock** [comment]
I can confirm that #102 solves this issue.

Here is the test case:

```rust
use node_bindgen::derive::*;
use fluvio_future::timer::sleep;

#[derive(Debug)]
struct NativeStore {
    val: String,
}

#[node_bindgen]
impl NativeStore {
    #[node_bindgen(constructor)]
    fn new() -> Self {
        Self { val: String::from("unknown") }
    }

    #[node_bindgen]
    async fn get(&self) -> String {
        sleep(std::time::Duration::from_micros(1)).await;
        self.val.clone()
    }

    #[node_bindgen]
    async fn put(&mut self, value: String) {
        sleep(std::time::Duration::from_millis(500)).await;
        self.val = value;
    }
}
```

and js

```js
(async () => {
    const store = new addon.NativeStore();
    await store.put("hello world");
    const val = await store.get();
    assert.strictEqual(val, "hello world")
})();
```

Without #102, the above will fail. Feel free to add this to the promises test or I can do it also.

**Comment by sehz** [comment]
Great! Please add this to promise test case

**Comment by sehz** [comment]
v4.0.0 is published to crates.io
