### ISSUE TITLE
Multiple buffer parameters produces error

### ISSUE THREAD

**Issue by mattcollier** [infinyon/node-bindgen#109]
This is using current master cbef86c624d9ae9a65d7b9626bd1a5885c8750b7 and `rustc 1.48.0 (7eac88abb 2020-11-16)`

I created this additional test function: https://github.com/mattcollier/node-bindgen/blob/buffer-multiple/examples/buffer/src/lib.rs#L87-L94

Which produces this error:
```
matt:~/fork/node-bindgen/examples/buffer$ nj-cli build
   Compiling nj-example-buffer v0.1.0 (/home/matt/fork/node-bindgen/examples/buffer)
error[E0499]: cannot borrow `js_cb` as mutable more than once at a time
  --> buffer/src/lib.rs:87:1
   |
87 | #[node_bindgen]
   | ^^^^^^^^^^^^^^^
   | |
   | mutable borrow starts here in previous iteration of loop
   | first borrow later used here
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0499`.
error: could not compile `nj-example-buffer`

To learn more, run the command again with --verbose.

```

**Comment by sehz** [comment]
Thanks for issue.  I can reproduce it

**Comment by sehz** [comment]
Using mutator ref for `js_cb` wasn't best idea.   Better design is create iterator for arguments

**Comment by mattcollier** [comment]
I just discovered another manifestation of this same issue, which is that in the following function signature, the `&[u8]` must be the last argument, or the same `js_cb` error occurs:
```rs
pub fn verify(public_key_bytes: String, signature_bytes: String, message: &[u8]) -> bool {...}
```

**Comment by sehz** [comment]
Yes, since procedure macro generates same code for functions.

**Comment by sehz** [comment]
Please test this fix

**Comment by mattcollier** [comment]
@sehz This is working for me.  Thank you very much!

**Comment by sehz** [comment]
v4.1.0 is released
