### ISSUE TITLE
Bulk removal of whitespace

### ISSUE THREAD

**Issue by mattcollier** [infinyon/node-bindgen#112]
Hello, it seems that there is a lot of whitespace in the files in this project.  Automatic removal of whitespace by editors makes for cluttered PRs.

Would it be possible for the maintainers to remove whitespace in this project in bulk to avoid this in the future?  I believe `cargo fmt` would make quick work of this.  It would be good to incorporate some linting step in CI to keep things in order going forward.

**Comment by sehz** [comment]
I agree, it's just oversight.   Will add fmt and clippy
