### ISSUE TITLE
Make it possible to regenerate bindgen work

### ISSUE THREAD

**Issue by palfrey** [infinyon/node-bindgen#12]
Currently this is hardcoded as https://github.com/infinyon/node-bindgen/blob/master/nj-sys/src/binding.rs with no docs/build.rs to redo it. It either needs some instructions on how to regenerate it, or ideally it gets rebuilt at build time.

**Comment by sehz** [comment]
I will remove generated code from check-in.  Will use build.rs to generate them at compile them.

**Comment by sehz** [comment]
Unfortunately, bindgen requires installation of LLVM which adds burden for developer.  I will update instruction on how to regenerate manually at least.

**Comment by sehz** [comment]
nj-sys crate now contain Makefile to re-generate binding.rs.   let me know if this doesn't work

**Comment by palfrey** [comment]
After doing `brew install llvm` and `export PATH=/usr/local/opt/llvm/bin:$PATH` I was able to run `make generate` successfully. However my binding.rs appears to be about half the size (38857 bytes vs. 60720). A copy of that is available at https://gist.github.com/palfrey/390e099f16c6774faa9063afa11829b7. Any ideas why the difference?

**Comment by sehz** [comment]
What version of LLVM are you using?  Existing binding.rs was generated using 9.0.0.1.   When I tried using latest version 10.0,  only difference is a single line with ```NAPI_VERSION```.  Also bindgen version is 0.52

**Comment by palfrey** [comment]
Last version I had installed with homebrew, which turns out to be 6.0.0. Probably worth documenting the version of LLVM used to generate binding.rs then?

**Comment by sehz** [comment]
done.  README.md updated with LLVM requirement

**Comment by palfrey** [comment]
Retried with more modern LLVM. LGTM.

**Comment by sehz** [comment]
closing
