### ISSUE TITLE
Discuss lifetime for JSValue for &str API

### ISSUE THREAD

**Issue by mattcollier** [infinyon/node-bindgen#129]
wrt this API: https://github.com/infinyon/node-bindgen/blob/master/nj-core/src/convert.rs#L232-L252

@sehz mentioned elsewhere that this is in connection with: https://github.com/infinyon/node-bindgen/issues/125

I'm still using a fork that implements an anonymous lifetime here: https://github.com/infinyon/node-bindgen/compare/master...mattcollier:anon_lifetime

I don't really understand the implications of one or the other except that the explicit lifetime breaks my code and I thought anonymous lifetimes were supposed to "do the right thing".  Perhaps the issue is that there's unsafe code involved?

Are the anonymous lifetimes specified for many of the other JsValue `impl` slated for being changed to an explicit lifetime as well?

**Comment by sehz** [comment]
Reason it breaks is that lifetime doesn't match in the declaration:

```
impl<'a> JSValue<'a> for &'a str {
    fn convert_to_rust(env: &JsEnv, js_value: napi_value) -> Result<Self, NjError> {
```

You care declaring this impl for `a` but are using `&JsEnv`,   `&` is kind of convenient notation if you don't have explicit time.  But in this you do, so need to declare as:
```
impl<'a> JSValue<'a> for &'a str {
    fn convert_to_rust(env: &'a JsEnv, js_value: napi_value) -> Result<Self, NjError> {
```

**Comment by mattcollier** [comment]
@sehz are you saying we need a patch to node-bindgen#master specify the lifetime as you described above on this line? 

https://github.com/infinyon/node-bindgen/blob/master/nj-core/src/convert.rs#L233

**Comment by sehz** [comment]
Yes

**Comment by mattcollier** [comment]
PR submitted, but the following code still does not build (without the use of the anonymous lifetime branch), but I believe you said that further changes are needed to the `as_value` API and/or the `get_property` API.  Is that right?

```
fn get_value_ref<'a>(o: &JsObject, key: &str) -> Option<&'a str> {
    let s = o.get_property(key).unwrap().unwrap();
    match s.get_property("value").unwrap() {
        Some(v) => match "value" {
            "datatype" => {
                let d = v.get_property("value").unwrap().unwrap();
                let result = d.as_value::<&str>();
                if let Err(_e) = result {
                    return None;
                }

                Some(result.unwrap())
            }
            _ => {
                let result = v.as_value::<&str>();
                if let Err(_e) = result {
                    return None;
                }

                Some(result.unwrap())
            }
        },
        None => None,
    }
}
```

**Comment by sehz** [comment]
Yes because `get_property` returns owned object,  need another api to return reference
