### ISSUE TITLE
Automatically derive TryIntoJs for structs

### ISSUE THREAD

**Issue by mkawalec** [infinyon/node-bindgen#147]
This improvement involves adding a new [derive macro](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macros) to `nj-derive` to automatically generate `TryIntoJs` instances for arbitrary Rust structs. The structs should consist of fields which implement `TryIntoJs` themselves and the struct should be converted to a JavaScript Object with fields named the same as the fields of the struct in Rust. 

Checklist:

- [ ] Create an implementation supporting structs with [named fields](https://docs.rs/syn/1.0.69/syn/enum.Fields.html#variant.Named)
- [ ] Serialize [unnamed fields](https://docs.rs/syn/1.0.69/syn/enum.Fields.html#variant.Unnamed) into an Array
- [ ] Include documentation

Bonus points:
- [ ] Tie the knot by implementing [`JsValue`](https://docs.rs/node-bindgen/4.3.0/node_bindgen/core/trait.JSValue.html) for effortless deserialization of values coming from JS
- [ ] Figure out a reasonable representation for enums and serialize them as well

**Comment by nicholastmosher** [comment]
This feature would be awesome! I wanted to quickly draw up some example use cases to make sure we're on the same page as to what the outcome of this issue would be. I'm imagining a scenario like the following:

We have some Rust struct with fields that all implement `JSValue` and `TryIntoJs`, annotated with `#[node_bindgen]`, as well as some function that takes this struct as an argument and/or returns it as a return value:

```rust
#[node_bindgen]
struct Foo {
    name: String,
    numbers: Vec<i32>,
}

#[node_bindgen]
fn capitalize_and_square(foo: Foo) -> Foo {
    let caps = foo.name.to_ascii_uppercase();
    let squared: Vec<i32> = foo.numbers.into_iter().map(|it| it * it).collect();

    Foo {
        name: caps,
        numbers: squared,
    }
}
```

And in Javascript, we would have an object whose fields are named the same which correspond to the types of `Foo`'s fields (I'll use typescript to illustrate types):

```typescript
type Foo = {
    name: string,
    numbers: number[],
};

interface RustLib {
    capitalizeAndSquare(foo: Foo): Foo
}
const rustLib: RustLib = require("./dist");

const myFoo = {
    name: "hello",
    numbers: [2, 4, 6],
};
const newFoo = rustLib.capitalizeAndSquare(myFoo);
assert.equal(newFoo.name, "HELLO")
assert.equal(newFoo.numbers, [4, 16, 36])
```

And then the second case to highlight would be tuple structs, which would be converted into a JS array similarly to how regular tuples are:

```rust
#[node_bindgen]
struct Foo(String, Vec<i32>);

#[node_bindgen]
fn capitalize_and_square(foo: Foo) -> Foo { ... }
```

With these corrresponding JS types:

```typescript
type Foo = [string, number[]];

const myFoo = ["hello", [2, 4, 6]];
const newFoo = rustLib.capitalizeAndSquare(myFoo);
assert.equal(newFoo[0], "HELLO")
assert.equal(newFoo[1], [4, 16, 36])
```

Let me know if that's approximately what you're thinking of doing here, or if there are any major differences in how you were going to go about it.

Also let me cc @sehz to keep him in the loop about this idea, I don't see any major blockers but I just want a second pair of eyes.

**Comment by mkawalec** [comment]
This is done, closing
