### ISSUE TITLE
Async/promise is not working on Windows.

### ISSUE THREAD

**Issue by federico-terzi** [infinyon/node-bindgen#15]
Hi,
After updating to the new version, the compilation process was flawless also on Windows.
That said, async/promise examples fail (whereas the others work correctly).

### Steps to reproduce
1. Navigate to the examples/promise folder
2. Run `nj-cli build`
3. Execute `node test.js`

The following error is reported:

```
addon.hello(5).then((val) => {
      ^

TypeError: napi call failed InvalidArg
    at Object.<anonymous> (C:\Users\Freddy\Documents\WiseTime\node-bindgen\examples\promise\test.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Thank you for your work, let me know if you need help to test something on Windows

**Comment by usagi** [comment]
Hmm, it's not repro to me whether it is good or bad. I tried two variations:

1. The current master branch of the infinyon/node-bindgen e5cfd5d4c86bb2e88fe5ed73dbd2a1f97360ad71
2. The merged your PR version of federico-terzi/node-bindgen ced70fea75f732a523969c337499a79f69399780

Log of building and running:

```
PS C:\Users\usagi\tmp\node-bindgen\examples\promise> nj-cli build
   Compiling nj-example-promise v0.1.0 (C:\Users\usagi\tmp\node-bindgen\examples\promise)
    Finished dev [unoptimized + debuginfo] target(s) in 3.80s
PS C:\Users\usagi\tmp\node-bindgen\examples\promise> node .\test.js
sleeping
sleeping
sleeping
throwing error
woke and adding 10.0
woke and adding 10.0
promise test succeed: 15
```

Related toolchain versions:

```
PS C:\Users\usagi\tmp\node-bindgen\examples\promise> nj-cli --version
fluvio 0.2.0
PS C:\Users\usagi\tmp\node-bindgen\examples\promise> node --version
v13.12.0
PS C:\Users\usagi\tmp\node-bindgen\examples\promise> rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

- Windows 10 19041.207

-----

It may seems that we need to find more certain repro conditions.

**Comment by federico-terzi** [comment]
The only difference in our toolchains is the node version, as I'm using v10.15.1
I'll try with your version, that could be it.

Thanks for looking that up

**Comment by federico-terzi** [comment]
Indeed with node 13.12.0 it works perfectly, thank you for the help.
That's pretty strange honestly, as I thought the N-API was somewhat stable between node versions.
At this point, it may be a good idea to add a notice to the readme with the minimum supported version.

**Comment by sehz** [comment]
Interesting. I am using NAPI version 5 supposedly work against v10.x,v12, v13.x: https://nodejs.org/api/n-api.html#n_api_implications_of_abi_stability.

I will update the doc.  Once CI is running can add different version of Rust/Node/OS.

**Comment by federico-terzi** [comment]
> Interesting. I am using NAPI version 5 which supposedly work against v10.x,v12, v13.x: https://nodejs.org/api/n-api.html#n_api_implications_of_abi_stability.

That's it then, as version 5 is compatible with >10.17.0 and I was running 10.15.1.

Thanks

**Comment by sehz** [comment]
Updated the doc with compatibility matrix.
