### ISSUE TITLE
Update changelog with latest changes (-> 4.3.0)

### ISSUE THREAD

**Issue by marcmo** [infinyon/node-bindgen#150]
you should keep your changelog in sync with your development, which makes it way easier for your users to keep track.
Missing:

* Use proper macro pattern for tuple impls (#143) 
* Add support for passing tuples between Node and Rust (#142) 
* Bump electron from 9.3.1 to 9.4.0 in /examples/electron (#135) 
* Update JSArrayBuffer to be usable in env.convert_to_rust::<JsArrayBuffer>

**Comment by sehz** [comment]
I fully agree.  Since you already identified them, can you create PR for it?
