### ISSUE TITLE
Latest `nj-cli` not published

### ISSUE THREAD

**Issue by futpib** [infinyon/node-bindgen#175]
I can reproduce #105. I see that it's fixed on master (almost a year passed since) and there even was a bump to `0.4.1` since, but `0.4.0` is the latest version on https://crates.io/crates/nj-cli so reinstalling `nj-cli` with `cargo install --force nj-cli` does not help.

**Comment by sehz** [comment]
Oops.  Published.  Can you try?

**Comment by futpib** [comment]
Thanks, it works!
