### ISSUE TITLE
Generate wrappers for external libraries?

### ISSUE THREAD

**Issue by tomleavy** [infinyon/node-bindgen#176]
Not sure if this is something that is already possible and maybe I missed it? I would like to be able to generate a Node wrapper around a library created by a 3rd party, without making changes to the original code. The workflow I'm looking for is something like this:

third-party-sdk - existing library
third-party-sdk-node - node wrappers around third-party-sdk + some javascript code in it's own repo

**Comment by nicholastmosher** [comment]
Hi @tomleavy, I think that what you're talking about should be possible, but I don't think it could be automated at the moment. I believe you could take a third-party crate and wrap it in a shim crate that has the appropriate `#[node_bindgen]` attributes to expose the functionality to Node. It's important to note that not all Rust patterns have an equivalent representation in JS and vice-versa, so a purely machine-generated set of bindings would probably not yield the best JS interface anyways.

But yes, your idea of creating a `third-party-sdk-node` crate should be fine, though you may be limited by how much of the interface of the `third-party-sdk` is public.

**Comment by tomleavy** [comment]
What would be the easiest way to create a shim that #[node_bindgen] can interact with? In this case most of the structs can probably be wrapped as-is. Would I need to re-define every one ?

**Comment by nicholastmosher** [comment]
You will need to import each type from your third-party crate and create a wrapper type around each one. For example:

```rust
use third_party::SomeType as NativeSomeType;

#[node_bindgen]
struct SomeType {
    inner: NativeSomeType,
}

#[node_bindgen]
impl SomeType {
    pub fn some_type_method(&self) -> ... {
        self.inner.some_type_method();
    }
}
```

You can see one example of this pattern here: https://github.com/infinyon/fluvio-client-wasm/blob/main/src/producer.rs

What crate are you trying to wrap?

**Comment by tomleavy** [comment]
This is helpful, thanks! It's a crate for internal use. I could in theory wrap everything in the codebase itself, but because I'm also wrapping into various other languages it gets messy to keep everything in one repo
