### ISSUE TITLE
Tokio runtime in node.js?

### ISSUE THREAD

**Issue by mycrl** [infinyon/node-bindgen#178]
Is the future of rust handed over to the node.js runtime for scheduling? If so, how can I use tokio runtime on rust lib?

**Comment by Brooooooklyn** [comment]
napi-rs support running tokio future on Node.js and cast it into Node.js Promise, see https://github.com/napi-rs/napi-rs/blob/napi%401.7.7/test_module/src/tokio_rt/read_file.rs
