### ISSUE TITLE
0.4.2 fails to build.

### ISSUE THREAD

**Issue by jaccarmac** [infinyon/node-bindgen#186]
I'm using Guix, so the environment might be a little funky. Nonetheless, I'm able to build 0.4.1.

`guix shell rust rust:cargo -- cargo install --list`

```
nj-cli v0.4.1:
    nj-cli
```

On the other hand, `guix shell rust rust:cargo -- cargo install nj-cli` fails:

```
error: there is no argument named `target`
   --> /home/jaccarmac/.cargo/registry/src/github.com-1ecc6299db9ec823/nj-cli-0.4.2/src/main.rs:105:37
    |
105 |         args.push(format!("--target={target}"));
    |                                     ^^^^^^^^
```

**Comment by morenol** [comment]
What is your rust version? It looks like you need to use `Rust=>1.58.0` 

https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1580-2022-01-13

**Comment by jaccarmac** [comment]
That would do it. Missed that there were string formatting changes happening.
