### ISSUE TITLE
Build on windows failed ( > node 18.x.x)

### ISSUE THREAD

**Issue by DmitryAstafyev** [infinyon/node-bindgen#203]
"Fresh" attempt to build with `nj-cli build` gives:
```
 Compiling chrono-tz-build v0.0.3
   Compiling http_req v0.8.1
   Compiling nj-build v0.2.4 (https://github.com/infinyon/node-bindgen.git?branch=master#cf382ddf)
   Compiling chrono-tz v0.6.3
   Compiling node-bindgen v5.0.0 (https://github.com/infinyon/node-bindgen.git?branch=master#cf382ddf)
   Compiling node-bindings v0.1.0 (C:\Users\username\projects\application_name\application\apps\rustcore\rs-bindings)
error: failed to run custom build command for `node-bindings v0.1.0 (C:\Users\username\projects\application_name\application\apps\rustcore\rs-bindings)`

Caused by:
  process didn't exit successfully: `C:\Users\username\projects\application_name\application\apps\rustcore\rs-bindings\target\debug\build\node-bindings-d5696
c941734570c\build-script-build` (exit code: 101)
  --- stdout
  downloading nodejs: https://nodejs.org/dist/v18.12.1
  /win-x64/node.lib to: "C:\\Users\\username\\AppData\\Local\\Temp\\node-v18.12.1.lib"

  --- stderr
  thread 'main' panicked at 'Download node.lib file failed: Parse(StatusErr)', C:\Users\username\.cargo\git\checkouts\node-bindgen-5f69c8b3ac8cdb9e\cf
382dd\nj-build\src\lib.rs:35:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
Looks like the script tries to download lib and fails with it. In the destination folder `C:\\Users\\username\\AppData\\Local\\Temp` file `node-v18.12.1.lib` exists but the size is 0. 
Well with next attempt to build with `nj-cli build` we have link error as result

```
error: linking with `link.exe` failed: exit code: 1136
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" "/DEF:C:\\
windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\username\\.rustup\\toolchains\\1.61.0-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\
(...cutted...)
\libcore.natvis" "/NATVIS:C:\\Users\\username\\.rustup\\toolchains\\1.61.0-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: C:\Users\username\AppData\Local\Temp\node-v18.12.1.lib : fatal error LNK1136: invalid or corrupt file

error: could not compile `node-bindings` due to previous error
```
A way around to fix it:
- manually download `node-v18.12.1.lib` from https://nodejs.org/dist/v18.12.1/win-x64/
- copy `node-v18.12.1.lib` into `C:\\Users\\username\\AppData\\Local\\Temp`
- build

It's more or less okay for local use but makes things really complicated on github actions.

Could you please take a look at it?

notes:
* "Fresh" - with removing `Cargo.lock` file
* tried with node 18.12.0, 18.8.0 and 19.x.x
* tried to uninstall/reinstall/repair node and vstools

**Comment by DmitryAstafyev** [comment]
[full_link_err.log](https://github.com/infinyon/node-bindgen/files/9995377/full_link_err.log)

**Comment by DmitryAstafyev** [comment]
@sehz hello there ) any ideas about this issue?

**Comment by DmitryAstafyev** [comment]
hello @asv7c2 , may be you have some ideas about it? )

**Comment by sehz** [comment]
Hi, @DmitryAstafyev,  windows are not the first tier we support.  It was done by another contributor a while back.
@simlay can you take look?

**Comment by DmitryAstafyev** [comment]
@sehz @simlay hello, could you please take a look on PR - https://github.com/infinyon/node-bindgen/pull/204
the issue was trivial - url
