### ISSUE TITLE
New Release to crates.io Compatible with Rust 1.79

### ISSUE THREAD

**Issue by AmmarAbouZor** [infinyon/node-bindgen#296]
Hello,

I've been using your crate and appreciate all the work that has gone into it. I recently updated to Rust 1.79 and since then building Node.js modules with the command `nj-cli build --release` with the `nj-cli` tool installed from [crates.io](https://crates.io/) fails with the error:
```bash
no cdylib target was founded
```
However, when I build the CLI tool directly from the GitHub master, it works fine. Therefore, I would appreciate it if you release a new version to crates.io since the current version there isn't compatible with Rust 1.79 anymore.

**Comment by sehz** [comment]
Sure. @morenol can you do release?

**Comment by morenol** [comment]
Released a new version of nj-cli 

@AmmarAbouZor Feel free to reopen this or create a new issue  if you find any issue with the new version

**Comment by AmmarAbouZor** [comment]
Very thanks for your quick response. Everything is working great as expected again :100:
