### ISSUE TITLE
Need the ability to pass arbitrary JSON

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/node-bindgen#3]
I need the ability to pass arbitrary number of parameters to an API:

var leader = <Object>

Option 1:
leader.consume( {offset: true,  maxBytes: 1024} );

Option 2:
leader.consume( {offset: true} );

Option 3:
leader.consume( );

**Comment by sehz** [comment]
fixed.

offset can take variation of:
    ///     string:     'earliest','latest'
    ///     number:   offset
    ///     json:      {
    ///                     offset:  <same string/number>,
    ///                     isolation:  'read_uncommitted','read_committed'
    ///                     max_bytes: number
    ///                 }

Currently only offset param is respected.  will create separate issue for other params.
