### ISSUE TITLE
Request: Windows support

### ISSUE THREAD

**Issue by usagi** [infinyon/node-bindgen#4]
This project is really excellent✨ But, in now, it would not work in Windows environment. I'm looking forward to support Windows.

For now, I got these errors using `nj-cli build` in Windows:

```powershell
PS C:\Users\usagi\tmp\node-bindgen\examples\function> nj-cli build
   Compiling flv-future-aio v1.0.0
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\fs\file_slice.rs:3:14
  |
3 | use std::os::unix::io::RawFd;
  |              ^^^^ could not find `unix` in `os`

error[E0433]: failed to resolve: could not find `sys` in `nix`
 --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\zero_copy.rs:7:10
  |
7 | use nix::sys::sendfile::sendfile;
  |          ^^^ could not find `sys` in `nix`

error[E0432]: unresolved import `nix::Error`
 --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\zero_copy.rs:8:5
  |
8 | use nix::Error as NixError;
  |     ^^^^^^^^^^^^^^^^^^^^^^ no `Error` in the root

error[E0412]: cannot find type `RawFd` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\fs\file_slice.rs:11:9
   |
11 |     fd: RawFd,
   |         ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\fs\file_slice.rs:18:20
   |
18 |     pub fn new(fd: RawFd,position: u64,len: u64) -> Self {
   |                    ^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\fs\file_slice.rs:34:25
   |
34 |     pub fn fd(&self) -> RawFd {
   |                         ^^^^^ not found in this scope

error[E0405]: cannot find trait `AsRawFd` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\fs\file_slice.rs:42:6
   |
42 | impl AsRawFd for AsyncFileSlice {
   |      ^^^^^^^ not found in this scope

error[E0412]: cannot find type `RawFd` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\fs\file_slice.rs:44:28
   |
44 |     fn as_raw_fd(&self) -> RawFd {
   |                            ^^^^^ not found in this scope

error[E0405]: cannot find trait `AsRawFd` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\zero_copy.rs:46:26
   |
46 | pub trait ZeroCopyWrite: AsRawFd {
   |                          ^^^^^^^ not found in this scope

error[E0425]: cannot find value `ft` in this scope
  --> C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\flv-future-aio-1.0.0\src\zero_copy.rs:93:9
   |
93 |         ft.await
   |         ^^ not found in this scope

error: aborting due to 10 previous errors

Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `flv-future-aio`.

To learn more, run the command again with --verbose.
thread 'main' panicked at 'copy failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\nj-cli-0.1.2\src\main.rs:69:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Please let me know if you know a workaround. I'm not hurry but I really expecting to success of the project. 👍

**Comment by sehz** [comment]
Thanks for feedback.  Yes, we intended to support all major platforms.  Looks like just needed to ensure dependent library can compile in non unix.

**Comment by sehz** [comment]
flv-future#1

**Comment by tom-haines** [comment]
echo comments about great project.
I had a look at this today locally, and found nj-bindgen doesn't use the code that is causes build issue on windows, in the sense that the sub-module can be excluded at least to build upstream on windows (exclude fs zero-copy etc) (via a modified submodule in my case).
I then hit issue that nj-cli assumes the dynlib will be match a pattern with `.d` (still investigating but maybe this info is helpful).

**Comment by sehz** [comment]
I pushed out change that use updated version of futures-ago library which fix build issue on Windows (at least can cross compile to Windows).   Can anyone try to build and test see if examples run since don't have windows VM?   Once we have CI support, this will not be issue.

**Comment by usagi** [comment]
Reporting:

Good news: The current master ( e319e3d3f8a08cd2b4a6f145e3d7a725ffa82aad ) is **works well in a compiling**.

Bad news: It's **not work in a linking** yet. 

Full log:

1.  `nj-cli build` in the example/function: https://gist.github.com/usagi/a54c18393c4e7ba4ce6e349d8590476d#file-nj-cli_win-msvc_2020-04-20-log
2. `dir ../target/debug/deps`: https://gist.github.com/usagi/a54c18393c4e7ba4ce6e349d8590476d#file-dir-result-log

**Comment by federico-terzi** [comment]
Hey @usagi,
I've managed to make it partially work on Windows (in the sense that most examples work, but not the ones that use Async).
I'll make a pull request in the evening so that you can examine the code.

Cheers

**Comment by federico-terzi** [comment]
I've opened the pull request, see: #14

**Comment by sehz** [comment]
Thanks for trying to fix the problem.    I am also looking at how neon binding did it: https://github.com/neon-bindings/neon/blob/master/crates/neon-build/src/lib.rs as well node.js build scripts.   Looks like I need to get Windows VM, so I can try it out on my machine.

**Comment by sehz** [comment]
Fixed.  Verified work against Node v14 both on Mac and Windows 10.
Please get updated version of nj-cli:
```cargo install -f nj-cli```
