### ISSUE TITLE
#[node_bindgen] is broken?

### ISSUE THREAD

**Issue by crone123** [infinyon/node-bindgen#41]
Hello,
I have tried to use this library with this test code:
```
use node_bindgen::derive::node_bindgen;

pub struct MyStruct
{
    pub x: i64,
    pub y: i64,
}

#[node_bindgen]
impl MyStruct
{
    #[node_bindgen(constructor)]
    fn new(x: i64, y: i64) -> Self
    {
        MyStruct
        {
            x: x,
            y: y
        }
    }
    #[node_bindgen]
    fn hello(&self)
    {
        println!("MyStruct hello !");
    }
}
```

It works with version 1.3.0, but not with version 2.1.1.
On this latest version, I got this error:
```
  --> src/lib.rs:15:1
   |
15 | #[node_bindgen]
   | ^^^^^^^^^^^^^^^- help: missing `,`
   | |
   | expected one of 8 possible tokens
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

In my case, the error concern the attribute used on the top of "impl MyStruct".
I have followed the examples, I don't know why it doesn't work.
Without this macro, it compiles but MyStruct is not available from nodejs.
Rust version: rustc 1.45.0-nightly (a74d1862d 2020-05-14) (on Linux 86_64)

Thank you !
Valentin CRÔNE

**Comment by sehz** [comment]
Thanks for bug report.  

Yes, I can reproduce it by nuking my cargo registry.

**Comment by sehz** [comment]
Yes, it works on 1.3.0 but not latest version

**Comment by sehz** [comment]
This is interesting.  Generated code looks ok and it even compiles but not from macro directly

**Comment by sehz** [comment]
fixed.  previous implementation of macro expansion include extra ```,```.  somehow it worked but I guess doesn't with latest version of quote library.

```cargo update``` and it should work.

**Comment by crone123** [comment]
Thank you !
Have I to change the version number in Cargo.toml or just cargo update?

**Comment by sehz** [comment]
Cargo update should be enough

**Comment by crone123** [comment]
Ok, it works, thank you ! :)
