### ISSUE TITLE
`nj-cli build` failed in a link-time with node-bindgen-2.1.1 and the latest toolchains

### ISSUE THREAD

**Issue by usagi** [infinyon/node-bindgen#46]
## Abstract

- node-bindgen-2.1.1 is not work in Windows.
- `nj-cli build` to be fail 100% in a link-time
    - 🚨 ```error: linking with `link.exe` failed: exit code: 1120```
    - The full log is here 👉 <https://gist.github.com/usagi/31b72fad5f5bf382d67b18be7f497047#file-node-bindgen-2-1-1-windows-error-log-L110>

## Repro.

1. $ `cargo install nj-cli`
2. $ `cargo new --lib e1`; $ `cd e1`
3. Edit: Cargo.toml
    - Append: In `[lib]`, `crate-type = ["cdylib"]`
    - Append: In `[dependencies]`, `node-bindgen = "2.1.1"`
    - Append: In `[build-dependencies]`, `node-bindgen = {version = "2.1.1", features = ["build"]}`
4. Edit: src/lib.rs

```rust
use node_bindgen::derive::node_bindgen;
/// add two integer
#[node_bindgen]
fn sum(first: i32, second: i32) -> i32 {
 first + second
}
```
5. $ `nj-cli build` ( to be failed on Windows )

## Additional infromations

- Windows 10 Version 2004 (OS Build 19041.330)
- powershell 7.1.0-preview.5
- rust:
    - toolchain `stable-x86_64-pc-windows-msvc`, `nightly-x86_64-pc-windows-msvc`
    - rustc `1.44.1 (c7087fe00 2020-06-17)`, `1.46.0-nightly (0c03aee8b 2020-07-05)`
- node-bindgen:
    - `[dependencies]`/[`build-dependencies`] 2.1.1
    - `nj-cli` fluvio 0.2.0
- Note: The same project be works fine on Arch Linux environment (rust-toolchain=stable/nightly-x86-64-unknown-linux-gnu).

----

- Blocking: https://github.com/infinyon/node-bindgen/issues/17#issuecomment-658381778

**Comment by sehz** [comment]
works for me.

```
cd examples\function
nj-cli build


```
* Windows 10 Version 2004 (OS Build 19041.421)
* Rust
    - tool chain: stable-x86_64-pc-windows-msvc
    - rustc 1.45.0 (5c1f21c3b 2020-07-13)
```

Can you try to upgrade to latest version of nj-cli?
```
cargo install --force nj-cli
```

and with latest version of rust?

**Comment by usagi** [comment]
Solved! I forgot the `build.rs` file in my repro project. The `build.rs` is not reqiured in Arch Linux environment and it was undocumented in the readme, thus I was late to notice about it.

Additional proposal: Add about the `build.rs` in Windows to the readme between the `Configuring Cargo.toml` section and the `Example` section.

**Comment by sehz** [comment]
Glad it worked.  I will add instruction on adding ```build.rs```.    Probably should add ```init``` commands to ```nj-cli``` to init repo
