### ISSUE TITLE
Build CI pipeline

### ISSUE THREAD

**Issue by sehz** [infinyon/node-bindgen#8]
First decided on GitHub Action or Travis.

Ability to build and test for following configuration:
*  OS: Mac, Windows, Linux
*  Node: Current version and LTS

Other considerations:
* Flexible
* Easier to extend
* Performant

**Comment by palfrey** [comment]
Pros on Travis:
- Better OS X support (versions before 10.15, as opposed to Github actions which only support 10.15)
- Much more readable UI, especially when you want to answer the question "what steps succeeded/failed for this PR/this branch"
- Already implemented as #11

Cons on Travis:
- OS X 10.15 still not there (see https://travis-ci.community/t/macos-catalina-10-15-support/7805) but should be available eventually...

I would note that for the Windows support I've seen the Travis+[Appveyor](https://www.appveyor.com/) combination be common. Travis [does have Windows support](https://docs.travis-ci.com/user/reference/windows/) but AFAIK it's still a bit beta. No idea of the Github Actions quality on that.

I'd also say that multiple Rust versions should be tested. Typical would be stable/beta/nightly and whatever your listed MSRV (Minimum Supported Rust Version) is, which isn't listed in the README yet. #11 does this for Travis, along with Node versions and Linux/OS X support.

**Comment by sehz** [comment]
Pros on GitHub Action:
* UI is integrated on GitHub, don't have to go another place to see status.
* Seems to gaining lots of feature and flexibility given GitHub has more resources
* Can build your runner

Cons:
* Too dependent on Github/Microsoft

I agree, we should support multiple stable/beta/nightly

**Comment by palfrey** [comment]
Any further thoughts on this @sehz?

**Comment by sehz** [comment]
OS X 10.15 seems to be major issue since we are using as our development machine.  Do know you when they are going to support that?

**Comment by palfrey** [comment]
Not a clue on 10.15. Last announcement from them said "mid December" and that was on 02/12/2019, and nothing since then on the forums. Presumably they'll deal with it at some point still, but no sense of timescales.

**Comment by sehz** [comment]
After some investigation and reading, I think Github Actions seems more flexible.  First version of smoke test workflow has been implemented.  Following matrix are supported:
* Rust [Stable/Nightly/Beta]
* Node [v10,v12]
* OS [Linux,Mac,Windows]

I will close pending pull request. 

Thanks for starting the effort.
