### ISSUE TITLE
Way to call a napi function not implemented in core crate

### ISSUE THREAD

**Issue by vasishath** [infinyon/node-bindgen#89]
I want to call a napi cleanup routine method `napi_add_env_cleanup_hook()`. This method gives a hook to perform any cleanup before a page is refreshed or is being navigated away. It is available in the bindings.rs but not implemented yet in the core crate. Is there a way to use the `napi_call_result!` macro directly to call this method from my lib ? Or do you plan to implement all the methods eventually ?

Thanks a lot 😊

**Comment by sehz** [comment]
I would be happy to add support for `napi_add_env_cleanup_hook` if you can provide sample code where it could be used.

**Comment by vasishath** [comment]
Yes sure. One such case would be a background thread running a TCP server. On refreshing the page, (this scenario will occur a lot during development) the module will be loaded again causing it to fail since the previous thread is already running. Stopping the thread in that hook will prevent this from happening.

**Comment by sehz** [comment]
I will add support for [cleanup hook apis](https://nodejs.org/api/n-api.html#n_api_cleanup_on_exit_of_the_current_node_js_instance`) in next release.

**Comment by sehz** [comment]
add better document `napi_call_result`

**Comment by sehz** [comment]
Published new version.  Please take look at `examples/cleanup`

**Comment by vasishath** [comment]
> Published new version. Please take look at `examples/cleanup`

Thanks a lot :)
