### ISSUE TITLE
Support for Buffer / Uint8Array Arguments

### ISSUE THREAD

**Issue by nickbabcock** [infinyon/node-bindgen#93]
Poking at node-bindgen, it appears that there is no way to write a function that accepts a nodejs buffer or Uint8Array.

Use case, hash some bytes either via:

```rust
#[node_bindgen]
fn hash(data: Vec<u8>) {}
```
or
```rust
#[node_bindgen]
fn hash(data: &[u8]) {}
```

**Comment by sehz** [comment]
Published new version.  Please take look at `examples/buffer`
