### ISSUE TITLE
Electron import [module].node is not a valid Win32 application.

### ISSUE THREAD

**Issue by nothingbutnetcode** [infinyon/node-bindgen#95]
Hi, 

Is there some idiot proof checklist to get modules built with node-bindgen to work with Electron?  I have been trying for the past day to get this to work without success.
I get this error when trying to import it: 
Error: node-loader:
Error: E:\dev\electron\serverman\.webpack\main/b911d8f8ccebb112db602d3caf3830fd.node is not a valid Win32 application.

However, the module *does* work from the node command line.

On windows with msvc toolchain and stable rust (1.47.0)
nj-cli v1.0.4
electron-build-env 0.2.0
Electron is v 10.1.3
node-loader v1.0.2

Many thanks

**Comment by sehz** [comment]
Hi, sorry to hear about your problem. 

Is it possible to share your webpack configuration?  Or better yet, complete sample code to demonstrate problem. That will make easier to troubleshoot the problem.   

We will also try to build sample electron app with web pack and guidelines for configuring `webpack1`

**Comment by nothingbutnetcode** [comment]
Hi, 
Thanks for your response - I will put a repo together tomorrow.

**Comment by nothingbutnetcode** [comment]
Nevermind, I am getting the same issue with neon bindings so it must have something to do with my setup.  Thanks anyway.
